### ISSUE TITLE
:start_hour not working

### ISSUE THREAD

**Issue by fazelmk** [excid3/combined_time_select#10]
<%= f.time_select :time, :combined => true,  :minute_interval => 30, :time_separator => "", :end_hour => 21,  :start_hour => 09 %>

if I remove :start_hour => 09 it works fine.

**Comment by idoo** [comment]
`start_hour: 6` works well for me

**Comment by fazelmk** [comment]
I don't remember what this is about anymore =D
Suppose they fixed in the meanwhile :)
