### ISSUE TITLE
Not working & deprecated with Rails 5

### ISSUE THREAD

**Issue by sreuterle** [excid3/combined_time_select#13]
Hi there, is anything planned to make this gem ready for Rails 5? There are some deprecation warnings:

> DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super.

Furthermore:
> ActionController::Parameters No Longer Inherits from HashWithIndifferentAccess

so that `parse_time_select!` does not work anymore.

**Comment by excid3** [comment]
Not currently, but I'd love to review a pull request if you're interested in submitting one. :)

**Comment by sreuterle** [comment]
I tried a little in the last days but can't dive deep enough to fix the parts, sorry :-/

**Comment by shakycode** [comment]
I have a use case for this with Rails 5 and will start to take a stab at it.
